Update ecosystem-angular.md
single-spa/single-spa.js.org pull request #343
Opened 2020-10-08 15:43 UTC by lee9019

Added parcel component usage in angular

2020-10-08 15:55 UTC, lee9019 commented
@joeldenning Could you check this?

2020-10-08 16:05 UTC, filoxo requested changes
Thanks for contributing! I left one comment about how to use the Parcel component. Can I also ask you to try to follow the same format and outline as [single-spa-react's Parcel docs](https://single-spa.js.org/docs/ecosystem-react/#parcels)?

2020-10-08 16:05 UTC, filoxo commented on website/versioned_docs/version-5.x/ecosystem-angular.md
> +In order to consume parcels created in other frameworks (vue, react) in angular, there is a angular parcel component available which can be used to fetch the vue or react parcel and add it to the DOM
This isn't correct. Parcels have been added to single-spa-angular's public API, see here: https://github.com/single-spa/single-spa-angular/blob/master/src/src/public_api.ts#L3-L4
You should instead be able to `import { ParcelModule, ParcelComponent } from 'single-spa-angular'` but I don't have an Angular app to validate that at the moment. Will you try out that syntax and update these docs?

2020-10-09 22:27 UTC, internettrans commented on website/versioned_docs/version-5.x/ecosystem-angular.md
> +In order to consume parcels created in other frameworks (vue, react) in angular, there is a angular parcel component available which can be used to fetch the vue or react parcel and add it to the DOM
Agreed. I don't think that that import works ever since we switched to ng-packagr instead of rollup for bundling single-spa-angular. We should not instruct users to copy/paste code, but rather to use it from their node_modules.

2020-11-09 22:07 UTC, joeldenning commented
The parcel component has been fixed, and there is a working example in https://github.com/single-spa/single-spa-angular/releases/tag/v4.7.0. @arturovt is planning on submitting a PR with documentation for it. I am closing this in favor of that PR

2020-11-09 22:07 UTC, closed without merging